name: TODO to Issue

on:
  push:

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert TODOs to Issues
        uses: alstr/todo-to-issue-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          AUTO_ASSIGN: true
          CLOSE_ISSUES: true
          NO_STANDARD: true
          LANGUAGES: ".github/todo-lang-text.yml"

